### ISSUE TITLE
How do I change the default voices?

### ISSUE THREAD

**Issue by ralyodio** [souzatharsis/podcastfy#101]
The default ones sound too bland and boring.

**Comment by ralyodio** [comment]
not obvious

**Comment by souzatharsis** [comment]
@CryptoCultCurt This has been fixed now. Please let me know if it now works for you.

**Comment by ralyodio** [comment]
so how do I add a custom voice?

**Comment by CryptoCultCurt** [comment]
It seemed it expected a copy of the entire config when I want to override something, so i pasted the default and made changes.   Sorry Python is not my strength, unsure if this error is me or a bug :).  

"Input to ChatPromptTemplate is missing variables {'input_texts'}.  Expected: ['conversation_style', 'dialogue_structure', 'engagement_techniques', 'input_text', 'input_texts', 'output_language', 'podcast_name', 'podcast_tagline', 'roles_person1', 'roles_person2', 'word_count'] Received: ['input_text', 'word_count', 'conversation_style', 'roles_person1', 'roles_person2', 'dialogue_structure', 'podcast_name', 'podcast_tagline', 'output_language', 'engagement_techniques']\nNote: if you intended {input_texts} to be part of the string and not a variable, please escape it with double curly braces like: '{{input_texts}}'.\nFor troubleshooting, visit: https://python.langchain.com/docs/troubleshooting/errors/INVALID_PROMPT_INPUT"

**Comment by souzatharsis** [comment]
Please update podcastfy to latest

pip install --upgrade podcastfy

**Comment by souzatharsis** [comment]
@CryptoCultCurt This should be fixed now even without updating podcastfy

Please let me know

**Comment by CryptoCultCurt** [comment]
Sorry - clearly I know python so little i had not upgraded correctly :).  Works like a champ now!  Amazing project, thanks.
