### ISSUE TITLE
[Question] does OpenAI TTS supports SSML?

### ISSUE THREAD

**Issue by kun432** [souzatharsis/podcastfy#111]
I generated audio with a pdf and custom config with Japanese and changing default TTS model like this:

```python
from podcastfy.client import generate_podcast

audio_from_local_pdf = generate_podcast(
    urls=["./sample.pdf"],
    tts_model="openai",
    conversation_config={
        "output_language": "Japanese",
        "text_to_speech": {
            "default_tts_model": "openai",
            "openai": {
                "default_voices": {
                    "question": "alloy",
                    "answer": "nova"
                },
                "model": "tts-1"
            },
            "audio_format": "mp3",
            "temp_audio_dir": "data/audio/tmp/",
            "ending_message": "それではまた次回お会いしましょう。"
        },
    },
)

embed_audio(audio_from_local_pdf)
```

The audio is generated in Japanese but includes some speech which is "speak" in English, and verbose output seems SSML tags are included.

```
[('<speak> 皆さん、こんにちは！PODCASTFYへようこそ - あなただけのAI音声ポッドキャスト！', '<speak> 今日のテーマは何ですか？'), (snip)
```

seems LLM generates transcripts including SSML tags and `clean_tss_markup` remove those before sendig those to TTS.

but in codes:

https://github.com/souzatharsis/podcastfy/blob/main/podcastfy/text_to_speech.py#L286-L290

In my understanding, OpenAI TTS does not support any SSML tags so I think it should remove all the tags. Do I misunderstand?

**Comment by kun432** [comment]
this does not always happen. Depending on transcripts generates by LLM, sometimes it includes "<speak>", sometimes not.

**Comment by souzatharsis** [comment]
Hi, the SSML markup is generated by llm hence not guaranteed to always be
generated.

What are you trying to achieve with the speak tag?

**Comment by kun432** [comment]
I mean no SSML tag should be passed to TTS generation especially for OpenAI because OpenAI TTS does not support SSML, I think. So `clean_tss_markup` should remove all SSML tag for OpenAI TTS, but it seems to keep some tags as `supported_tags`.

**Comment by souzatharsis** [comment]
But is it compromising audio generation in your experience? That is, is the
speaker actually saying a tag out loud?

Anyhow that's a good point, I've been thinking about dropping all TTS
markups since modern TTS models don't need that.

**Comment by kun432** [comment]
>That is, is the speaker actually saying a tag out loud?

yep, it sounds like "speak (japanese speech continues)". This happens not always like it sometime is spoken, usually ignored, depends on how TTS model recognize those.

so this might happen in non-english situation.

**Comment by souzatharsis** [comment]
That's good feedback. I'll make sure all markup is dropped.

**Comment by souzatharsis** [comment]
For now I managed to clean up speak tag. I'll make sure all markup is dropped at the LLM level in the future.

**Comment by souzatharsis** [comment]
solved in latest release; no longer generating TTS markup
