### ISSUE TITLE
Enable ease of switch of llm base model

### ISSUE THREAD

**Issue by souzatharsis** [souzatharsis/podcastfy#115]
using litellm

**Comment by jeremyklein** [comment]
Why litellm?

**Comment by souzatharsis** [comment]
I am open to suggestions. Would love to hear your recommendation.

**Comment by ralyodio** [comment]
most people use ollama i think

**Comment by edferr** [comment]
LMstudio, or any standard /v1/completions endpoint provider would be nice.

**Comment by OrphBean** [comment]
Kobold, Ooobabooga, LM studio would be great backends for this as they host a wide variety of models in multiple formats.

**Comment by souzatharsis** [comment]
I'm leaning towards ollama and enabling running any GGUF models from Huggingface.co

**Comment by edferr** [comment]
/v1 api interfaces are pretty standard these days. i just think ollama is a little underdeveloped compared to LMStudio as well. especially in the 'user interface on windows' category. LMStudio also has a built in graphic list of LLMs to choose from their own curated hugging space. ollama is CLI based, and actually choosing the quant you want usually involved a manual web browser trip to huggingface to look up whats available for that model. also LMStudio does updates and live log viewing quite nicely. Team Ollama has had months to polish their product, and there is little evidence of much polishing.

**Comment by souzatharsis** [comment]
LiteLLM + Langchain would be more straightforward:

https://docs.litellm.ai/docs/langchain/

We wouldn't need an additional API Key as in openrouter
We don't need to instantiate separate classes.
We simply pass the base model name and we're done.

Of course, this is assuming the user prefers having individual API Keys per model instead of a single one for all (e.g. openrouter).

```python
os.environ['OPENAI_API_KEY'] = ""
chat = ChatLiteLLM(model="gpt-3.5-turbo")

messages = [
    HumanMessage(
        content="what model are you"
    )
]
chat.invoke(messages)
```

**Comment by souzatharsis** [comment]
Related #127

**Comment by souzatharsis** [comment]
This is done. Would love your feedback:

https://github.com/souzatharsis/podcastfy/blob/main/usage/how-to.md#custom-llm-support
