### ISSUE TITLE
latest version sounds computer generated

### ISSUE THREAD

**Issue by ralyodio** [souzatharsis/podcastfy#122]
THe quality of the podcast audio has gone down, it sound very artificial.

```
word_count: 3000
conversation_style:
  - humorous
  - analytical
podcast_name: Byte Broadcast
podcast_tagline: "Byte Broadcast, your weekly gateway to the intersection of web development, artificial intelligence, and cryptocurrency, where complex concepts are decoded into byte-sized insights."
engagement_techniques:
  - cliffhangers
  - vivid imagery
  - audience prompts
creativity: 0.7
```

**Comment by souzatharsis** [comment]
I've updated the default tts-model to be Microsoft's Edge ('edge'), so it's free and it does not require an API Key.

Feel free to try other models by setting tts-model to 'openai' or 'elevenlabs'. Both will require API Keys.

Please let me know if that helps.

**Comment by ralyodio** [comment]
How do I switch to eleven labs? I have an api key.

**Comment by souzatharsis** [comment]
CLI:

   1.

   python -m podcastfy.client --url https://example.com/article1 --url
https://example.com/article2 --tts-model elevenlabs


Package:

audio_file_multi = generate_podcast(
	urls=[urls],
    tts_model="elevenlabs")

**Comment by ralyodio** [comment]
thanks
