### ISSUE TITLE
Add openAI and Anthropic API for text generation

### ISSUE THREAD

**Issue by OrphBean** [souzatharsis/podcastfy#127]
It would be great to have access to OAI and Anthropic for text gen. I have assistants on OAI set up specifically for technical translation. o1 mini is far superior to Gemini for generating highly detailed podcasts. I am using Podcastfy a lot for academic podcast generation and translation - but i am generating transcripts using o1 mini as it has higher quality output and then using gpt4o assistant that has technical language bilingual glossary for translation accuracy.

This is such a great software and resource. I have made my own basic .bat file that makes the input and function selection a lot easier. Are you going to make a gradio front end like the great huggingface demo?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/podcastfy) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/souzatharsis/podcastfy/issues/127">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/souzatharsis/podcastfy/issues/127/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/souzatharsis/podcastfy/issues/127/pledge.svg">
</picture>
</a>

**Comment by souzatharsis** [comment]
Thanks for sharing your experience.

Yes, adding OAI is a high priority.

I released a gradio/HF app yesterday. See usage section of README.

Would love your feedback!

**Comment by OrphBean** [comment]
It worked for me once - but now it will not. I have uploaded 10 pdfs to the HF demo and it processes for a few seconds then returns nothing. The first attempt worked well though - only with a single pdf. Not sure what is going on as no console

**Comment by souzatharsis** [comment]
Thanks, I've created an issue in the gradio app repo and will prioritize it
ASAP.

https://github.com/souzatharsis/podcastfy-demo/issues/2

**Comment by OrphBean** [comment]
I've just done a fresh install - I'm pretty new to installs from github but can find my way around - create .bat files and do the basics. 

The latest install puts the podcastfy folder inside my site packages inside my env. I have moved it back to the root folder for convenience - as that's where all the data is at.

The biggest hurdle to me using the full suite of tools on offer is the lack of a UI. I imagine that is very much on your radar given your HF implementation.

I am fully using the transcript tool - made like 20 podcasts with it using OAI. I had to adapt it to handle Chinese characters as my use case is making bilingual podcasts for use with native Chinese speakers.

I'm actually pretty busy otherwise I'd be putting more time into testing and experimenting.

**Comment by OrphBean** [comment]
basically the options I would want in the UI are
1. LLM dropdown
2. Prompt dropdown (to a folder of prompts and custom prompts)
3. Source doc folder path (pdf and txt)
4. Output language.
5. Translate generated transcript (So there is an accurate translation of previously generated transcript)
6. Upload transcript
7. The rest of the options you have already in the HF demo.

This is particular to my use case - but i think the ability to create bilingual podcasts - so its a translation of, rather than a new generation, is a solid tool that would have a lot of utility.

Being able to direct it to a folder with all the docs in it is a good quality of life feature. 

Love your work!

**Comment by souzatharsis** [comment]
@OrphBean that's for sharing your use case!

podcastfy is focused on programmatic use and I'd love to hear your needs!
for UI development though I'd refer you to Open Notebook which offers an amazing UI and uses podcastfy in the backend:

https://github.com/lfnovo/open-notebook

Feel free to reach out to the author @lfnovo who has been very active

**Comment by OrphBean** [comment]
Great! Thanks for the link and clarity of your project. I'll jump over there!

**Comment by albertaleksieiev** [comment]
Hey all! You have an amazing product, but why do you only use Gemini? Is it more capable for this task rather than Claude and OpenAI? 

Thank you!

**Comment by souzatharsis** [comment]
Hello, thanks for your question.
Gemini pro was the first model because of its long context window (2M), so we can support processing large number of input sources/content.

Enabling other base models should be a straight-forward update since we are using langchain.

Would you be excited to solve this issue?

**Comment by albertaleksieiev** [comment]
I'll take a look - this should be straightforward to implement.

Btw after checking my Gemini console metrics, I noticed I'm only using around 8K characters, which suggests the 2 million token context window might be oversized for typical usage patterns.
![image](https://github.com/user-attachments/assets/9f39f4d0-2c6c-453c-a44d-760c43c75e6e)

**Comment by souzatharsis** [comment]
Agreed. And chances are openai and Claude 3.5 Sonnet new will generate much
richer transcripts.

Adding them will be a great value add.

I am thinking they all implement langchains chatmodel so we can have that
as common interface.

**Comment by souzatharsis** [comment]
Or should we move to openrouter + langchain. Sounds the way to go to enable
seamless integration with any openai compatible api model

***@***.***/openrouter-langchain-leverage-opensource-models-without-the-ops-hassle-9ffbf0016da7

**Comment by albertaleksieiev** [comment]
```
from langchain_groq import ChatGroq
from langchain_anthropic import ChatAnthropic
from langchain_openai import ChatOpenAI
```

And add them to LLMBackend should be fine. Also by adding Groq gives the blazing speed for podcast generation.

**Comment by souzatharsis** [comment]
Sounds good!

**Comment by souzatharsis** [comment]
LiteLLM + Langchain would be more straightforward:

https://docs.litellm.ai/docs/langchain/

1. We wouldn't need an additional API Key as in openrouter
2. We don't need to instantiate separate classes in your example

We simply pass the base model name and we're done.

Of course, this is assuming the user prefers having individual API Keys per model instead of a single one for all (e.g. openrouter).

```python
os.environ['OPENAI_API_KEY'] = ""
chat = ChatLiteLLM(model="gpt-3.5-turbo")

messages = [
    HumanMessage(
        content="what model are you"
    )
]
chat.invoke(messages)
```

**Comment by souzatharsis** [comment]
This issue is a subset of #115

**Comment by souzatharsis** [comment]
Hi, This is done.

You can now generate podcast transcripts from 100+ LLM models:

https://github.com/souzatharsis/podcastfy/blob/main/usage/how-to.md#custom-llm-support

Would love your feedback.

**Comment by albertaleksieiev** [comment]
Oh wow! Amazing work, thank you!

**Comment by souzatharsis** [comment]
I would love to hear your feedback: What base model should we recommend
users to utilize?

**Comment by albertaleksieiev** [comment]
Sure! Here's what I found so far:

##### GPT-4o Preview
- Generates longer conversations
- Produces 2-3x more dialogs compared to GPT-4o base

##### GPT-4o Base
- Generates good quality content
- Similar performance to Gemini
- Appears to be the optimal choice

##### Claude 3.5 Sonnet
- Generates notably shorter content

So it looks like gpt-4o or Gemini is the optimal choice. However if you can pay 1$ at average for podcasts, o1 preview looks like the best choice.

### Sample Outputs
- [Sonnet 3.5 Sample](https://audio.com/albert222/audio/podcast-sonnet-35)
- [o1 Preview Sample](https://audio.com/albert222/audio/podcast-o1-preview)
- [GPT-4o Sample](https://audio.com/albert222/audio/podcast-gpt-4o)

**Comment by souzatharsis** [comment]
Thank you so much for your feedback and analysis!

Is it OK if I add it to the official documentation?

If yes, would you mind sharing in out used (url/pdf/text) and gemini
output with me?

I've noticed Sonnet did not follow the instructions well since the output
lacked Conclusion section. o1 indeed was impressive though costly.

Thanks!

**Comment by albertaleksieiev** [comment]
Sure, sounds good!

This is a link to Gemini - https://audio.com/albert222/audio/podcast-gemini
A source PDF - [2006WICC.pdf](https://github.com/user-attachments/files/17662866/2006WICC.pdf)
