### ISSUE TITLE
Setting default Edge voices

### ISSUE THREAD

**Issue by ronnyskog** [souzatharsis/podcastfy#132]
My settings for Edge voices do not seem to take effect. I specify Norwegian voices, but they clearly speak with an American accent, apparently using the default US voices despite my settings. Am I doing this wrong? Or is it a bug?

podcast_config = {
    "word_count": 100,
    "conversation_style": ["Engaging", "Fast-paced", "Enthusiastic", "Educational"],
    "roles_person1": "Interviewer",
    "roles_person2": "Subject matter expert",
    "dialogue_structure": [
        "Topic Introduction",
        "Summary of Key Points",
        "Discussions",
        "Q&A Session",
        "Farewell Messages",
    ],
    "podcast_name": "Printaga Podcast",
    "podcast_tagline": "Hvor kommer Halloween fra?",
    **"output_language": "Norwegian",**
    "user_instructions": "The podcast is in Norwegian. Use the Norwegian language. Make if fun and engaging",
    "engagement_techniques": [
        "Rhetorical Questions",
        "Personal Testimonials",
        "Quotes",
        "Anecdotes",
        "Analogies",
        "Humor",
    ],
    "creativity": 0.7,
    "text_to_speech": {
        "temp_audio_dir": "./data/audio/tmp/",
        "ending_message": "Takk for at du lytter til min Podcast!",
        "default_tts_model": "edge",
        **"edge_tts": {
            "default_voices": {
                "question": "nb-NO-FinnNeural",
                "answer": "nb-NO-PernilleNeural",
            },**
        },
        "audio_format": "mp3",
    },
}

**Comment by souzatharsis** [comment]
Hi, thanks for sharing a reproducible example.
In my experience, Microsoft Edge (is free but) has the lowest quality among
TTS models available.
The best is elevenlabs, which was the TTS model used in the French and
Brazilian Portuguese examples in the repo.
You can also try OpenAI's but 11labs is the recommended option for
multilinguality.
<http://linkedin.com/in/tharsissouza>

**Comment by souzatharsis** [comment]
Hi, there is a mistake in your config dictionary.
You should add the voice name or id to default_voices, question and answer.
You are sending empty strings, hence podcastfy is taking the default values
which are US-based.

"default_voices": {
"question": "", # add voice name or voice id here
"answer": "", # add voice name or voice id here
},


<http://linkedin.com/in/tharsissouza>

**Comment by souzatharsis** [comment]
Thanks for sharing a reproducible example.

Try:

my_podcast = generate_podcast(urls=urls,
conversation_config=podcast_config, tts_model='elevenlabs')

There is a bug where the "default_tts_model" from config is not being
considered but if you pass the TTS model using the tts_model param it
should work.

Please let me know!
<http://linkedin.com/in/tharsissouza>

**Comment by souzatharsis** [comment]
Bug solved in latest release

**Comment by souzatharsis** [comment]
thanks for the follow up

should be fixed in latest release now
