### ISSUE TITLE
generate from transcript only

### ISSUE THREAD

**Issue by pfloresl** [souzatharsis/podcastfy#148]
Hi, I am trying to use the Python -m podcast.client --URL https://example.com/article1 --transcript-only command line,  but it is not working. It is generating a small mp3 that appears to be invalid.   The transcript is created by me using the format of your transcripts: <Person1> </Person1><Person2 > </Person2>.   Additional how can i specify the audio voices?  I created  conversation_config.yaml but it still does not work. Thank you. Great stuff.

**Comment by souzatharsis** [comment]
Hi, thanks for opening this issue.

Please share additional data so your issue is reproducible:

1. transcript file
2. conversation_config.yaml file
3. full CLI command used

<http://linkedin.com/in/tharsissouza>

**Comment by pfloresl** [comment]
Thank you. It was my mistake. My transcript tags were not correctly closed. To confirm one of the questions, conversation_config.yaml is used for selecting the audio? will passing it in the command line also work?  Thank you,

**Comment by souzatharsis** [comment]
Thanks for the clarification and I'm glad it's working for you.

Yes, passing conversation_config.yaml should work for CLI.
The Python package, on the other hand, expects a dictionary instead.
Please close the issue if your original problem has been solved.

Thanks!

<http://linkedin.com/in/tharsissouza>

**Comment by pfloresl** [comment]
Thank you
