### ISSUE TITLE
Limitation on Podcast Length with Higher Word Counts

### ISSUE THREAD

**Issue by KlaasYntema** [souzatharsis/podcastfy#166]
First of all, thank you for this impressive package! I’ve encountered a possible issue when attempting to create longer audio outputs. Specifically, when I set a high word count (e.g., 5000 words) to generate a podcast of around 10 minutes, the resulting audio file only runs between 2 to 3 minutes.

Could you clarify if I might be configuring something incorrectly, or if there’s currently a limitation on generating longer audio outputs?

Thank you for your help!

This is my configuration:
```
config = {
    'word_count': 5000, 
    'conversation_style': ['Engaging', 'Fast-paced', 'Enthusiastic', 'Educational'], 
    'roles_person1': 'Interviewer', 
    'roles_person2': 'Subject matter expert', 
    'dialogue_structure': ['Topic Introduction', 'Summary of Key Points', 'Discussions', 'Q&A Session', 'Farewell Messages'], 
    'podcast_name': 'Podcast',
    'podcast_tagline': 'De ... podcast', 
    'output_language': 'Dutch', 
    'user_instructions': 'Make if fun and engaging, only talk about chapter 1.1, 1.2 and 1.3 from the provided pdf.', 
    'engagement_techniques': ['Rhetorical Questions', 'Personal Testimonials', 'Quotes', 'Anecdotes', 'Analogies', 'Humor'], 
    'creativity': 0.7, 
    'text_to_speech': {'temp_audio_dir': './data/audio/tmp/', 'ending_message': "Bedankt voor het luisteren!", 'default_tts_model': 'openai', 'openai': {'default_voices': {'question': 'alloy', 'answer': 'onyx'}, 'model': 'tts-1-hd'}, 
    'audio_format': 'mp3'}
}
```

**Comment by souzatharsis** [comment]
LLMs are known for their limited output number of tokes size.
Long form podcast generation has become an issue of the highest priority since multiple requests have been made.

I'll work on it next; No clue what the solution will be since there isn't any known best practice but it will be fun to develop a robust solution for it.

**Comment by souzatharsis** [comment]
I've managed to implement longform podcast generation. Would love your feedback: 

https://github.com/souzatharsis/podcastfy/discussions/168

**Comment by souzatharsis** [comment]
This has been implemented - I'd love feedback!

See https://github.com/souzatharsis/podcastfy/blob/main/usage/how-to.md#how-to-generate-longform-podcasts

## [0.3.6] - 2024-11-13

### Added
- Add longform podcast generation support
  - Users can now generate longer podcasts (20-30+ minutes) using the `--longform` flag in CLI or `longform=True` in Python API
  - Implements "Content Chunking with Contextual Linking" technique for coherent long-form content
  - Configurable via `max_num_chunks` and `min_chunk_size` parameters in conversation config
  - `word_count` parameter removed from conversation config as it's no longer used
