### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by ionpetro** [souzatharsis/podcastfy#169]
Can not access https://www.podcastfy.ai/

**Comment by souzatharsis** [comment]
Hello, thanks for your question.

podcastfy.ai simply redirects to this very github repo

What are you looking for?

**Comment by ionpetro** [comment]
hey, my bad. Any api documentation or playground?

**Comment by souzatharsis** [comment]
[Paper](https://github.com/souzatharsis/podcastfy/blob/main/paper/paper.pdf) | [Python Package](https://github.com/souzatharsis/podcastfy/blob/59563ee105a0d1dbb46744e0ff084471670dd725/podcastfy.ipynb) | [CLI](https://github.com/souzatharsis/podcastfy/blob/59563ee105a0d1dbb46744e0ff084471670dd725/usage/cli.md) | [REST API](https://github.com/souzatharsis/podcastfy/blob/59563ee105a0d1dbb46744e0ff084471670dd725/usage/api.md) | [Web App](https://huggingface.co/spaces/thatupiso/Podcastfy.ai_demo) | [Feedback](https://github.com/souzatharsis/podcastfy/issues)
