### ISSUE TITLE
set up basic CICD 

### ISSUE THREAD

**Issue by brumar** [souzatharsis/podcastfy#17]
github actions would look like a natural choice. Running the tests would be the first step.
Possibly related to https://github.com/souzatharsis/podcastfy/issues/7

**Comment by souzatharsis** [comment]
Done .github/workflows/python-app.yml

I've set it up using containers.
I've configured such that PRs are automatically tested before they can be merged.

I am skipping two kinds of tests:
1. paid TTS backends
2. youtube scraper, since it gets blocked by github machines IPs
