### ISSUE TITLE
audio creation gives an empty(261 bytes) mp3

### ISSUE THREAD

**Issue by ajaco56** [souzatharsis/podcastfy#170]
when using this CLI cmd:

python3 -m podcastfy.client --transcript /Users/Andreas/deep_dive/data/transcripts/transcript_2dcea9b591e340bda5778e323822e7ad.txt -tts openai -l --conversation-config conversation_config.yml

also with -tts edge, same result

it ends with an empty mp3 , i added my openai key to a .env file and this in config.yml:

  openai:
    default_voices:
      question: "echo"
      answer: "shimmer"
    model: "tts-1-hd"

ao

Please help

**Comment by ajaco56** [comment]
Hi Thársis,

I figured it out , the transcript appears to need <Person1>...</Person1> and <Person2>...</Person2>  tags 
After I added those to my handcrafted dialog file it started to work

Still I wonder why some of my fully, i.e. taking from an url, did not create those tags in the transcript

Cheers

Andreas

**Comment by souzatharsis** [comment]
Edge is the most limited model available. Consider using more advanced models.
As of today, our recommendation is to use `tts_model = geminimulti`, our multispeaker model available in v0.4.0.

- All sample audio in README have been updated to use the new TTS Model. Added some longform podcasts too.

- I've updated python notebook describing longform podcast + new Google TTS model work:

https://github.com/souzatharsis/podcastfy/blob/main/podcastfy.ipynb

**Comment by ajaco56** [comment]
Hi ThársisThanks for the explanation and recommendationI have a Gemini API key now, will see it’s benefits!RegardsAndreasmy email: ***@***.*** 16 Nov 2024, at 20:33, Tharsis Souza ***@***.***> wrote:﻿
Edge is the most limited model available. Consider using more advanced models.
As of today, our recommendation is to use tts_model = geminimulti, our multispeaker model available in v0.4.0.


All sample audio in README have been updated to use the new TTS Model. Added some longform podcasts too.


I've updated python notebook describing longform podcast + new Google TTS model work:


https://github.com/souzatharsis/podcastfy/blob/main/podcastfy.ipynb
