### ISSUE TITLE
Longform podcast gemini TTS integration

### ISSUE THREAD

**Issue by jashton12** [souzatharsis/podcastfy#187]
The trouble I am having with longer form content is that the TTS APIs have token limits. The Gemini TTS max is 5000 tokens and OpenAI 4096. With Elevenlabs and Edge you can push up to 10K but the quality of speech is significantly less natural. Elevenlabs is not bad but still nothing close to Gemini in my opinion. Does anybody have a fix or suggestion to circumvent this so that I can still use the gemini TTS API?

_"Failed to generate audio: 400 Either input.text or input.ssml is longer than the limit of 5000 bytes. This limit is different from quotas. To fix, reduce the byte length of the characters in this request, or consider using the Long Audio API: https://cloud.google.com/text-to-speech/docs/create-audio-text-long-audio-synthesis."_

I have not tried the long audio synthesis API but my intuition is that it wouldn't work out of the box and may deliver a lower quality of audio too. I may test and report back, but in the meantime any suggestions would be greatly appreciated. I am looking at how to adjust the code so that multiple API calls are made to gemini with the different parts that are generated with longform=True, and then stitching them together.

Thank you for this package, it's brilliant!

**Comment by souzatharsis** [comment]
I've implemented this for the Google multispeaker model.

Try passing geminimulti to tts_model param.

**Comment by jashton12** [comment]
I had not pulled the most recent commit! It is working well now, thank you for this!

**Comment by souzatharsis** [comment]
Cheers!

**Comment by DomoMKT** [comment]
"try [www.nemesyslabs.com](https://www.nemesyslabs.com) for a free text-to-speech solution with no token limits and high-quality speech!"
