### ISSUE TITLE
google TTS "geminimulti"  says gemini API key is invalid in production env and not local 

### ISSUE THREAD

**Issue by baznta** [souzatharsis/podcastfy#190]
`def generate_podcast_from_transcript(user_id, topic):
    # Generate podcast from URL
    config = {
    'conversation_style': ['Engaging', 'Fast-paced', 'Enthusiastic', 'Educational'], 
    'roles_person1': 'Interviewer', 
    'roles_person2': 'Subject matter expert', 
    'dialogue_structure': ['Topic Introduction', 'Summary of Key Points', 'Discussions', 'Q&A Session', 'Farewell Messages'], 
    'podcast_name': 'edify podcast', 
    'podcast_tagline': topic, 
    'output_language': 'English', 
    'user_instructions': 'ensure it is thought provoking, educative and engaging ', 
    'engagement_techniques': ['Thought provoking questions', 'deep dives', 'detailed explanations', 'real world examples', 'curious'], 
    'creativity': 0.8
    }
    raw_text = transcript_store.get_transcript(user_id=user_id,topic=topic)
    audio_file_from_raw_text = generate_podcast(text=raw_text,tts_model="geminimulti",conversation_config= config
                                                )

    return audio_file_from_raw_text`
    
    
    this works well on my device I have the API keys in a .env when I go to prod " google cloud build" after deployment it returns 
    
    `{
  "detail": "Invalid argument provided to Gemini: 400 API key not valid. Please pass a valid API key. [reason: \"API_KEY_INVALID\"\ndomain: \"googleapis.com\"\nmetadata {\n  key: \"service\"\n  value: \"generativelanguage.googleapis.com\"\n}\n, locale: \"en-US\"\nmessage: \"API key not valid. Please pass a valid API key.\"\n]"
}`

**Comment by souzatharsis** [comment]
Make sure your.env file is available in your prod server

Alternatively:

Try running export <api key label > = api key in your shell before using
the api.

**Comment by baznta** [comment]
i have a .env.yaml file for adding all keys to the prod server and a cloudbuild.yaml for building the image

**Comment by ralyodio** [comment]
might be ip based authentication

Anthony
408-656-2473
https://profullstack.com

**Comment by souzatharsis** [comment]
Hi,

It needs to be called .env

**Comment by baznta** [comment]
Hello, please does it also need to follow the conventional 

api_key_label = API key or can I stick to the yaml style of api_key_label : "Api key"  ?

**Comment by baznta** [comment]
Thank you this works im  greatful. i am now faced with a new error during audio processing 


`
  "textPayload": "ERROR:podcastfy.text_to_speech:Error during audio processing: [Errno 2] No such file or directory: 'ffprobe'",
  `
  
  
  
   this is from the ffmpeg package I had to install locally and add to my system vars(windows). My question is please how do I install this on gcp I am using the fully managed option "cloud run" and CloudBuild from a dockerfile. Thanks for the help @souzatharsis

**Comment by baznta** [comment]
thanks, @souzatharsis @ralyodio  it works fine now. Great work
