### ISSUE TITLE
google tts multi-speaker (geminimulti) permission error

### ISSUE THREAD

**Issue by arashnh11** [souzatharsis/podcastfy#209]
@souzatharsis as of 12/07 I see this permission error when hitting the v1beta1 endpoint for the geminimulti. Any thoughts?

"error": {
    "code": 403,
    "message": "The caller does not have permission",
    "status": "PERMISSION_DENIED"

**Comment by souzatharsis** [comment]
Hi have you enabled TTS for your api in Google cloud settings?

Please see
https://github.com/souzatharsis/podcastfy/blob/main/usage/config.md#setting-up-google-tts-model

**Comment by arashnh11** [comment]
Yes, I have the APi enabled and the API key restricted to the TTS API. The
standard TTS model (v1) works fine. The v1beta1 seems to come from a
different endpoint and that gives a permission error. I am wondering if
there is a temporary outage or what?
I may still be missing something if not

**Comment by souzatharsis** [comment]
Google Cloud can be a bit confusing. Last time I checked there were two
Text-to-speech API options with the same identical names. Try enabling
both...

Best Regards,

--
Thársis
souzatharsis.com <http://www.souzatharsis.com/>
<http://linkedin.com/in/tharsissouza>

**Comment by successful-fella** [comment]
Interesting. I made absolutely no changes, podcastify was able to generate audios a few days back. Today I just replaced raw text with one copied from an article and I am getting the same 403 caller does not have permission error. Anyone else?

**Comment by arashnh11** [comment]
I informed the Google TTS team about the issue earlier this week and they are investigating. I will report back here if any update/resolution.

**Comment by souzatharsis** [comment]
Thank you so much.

**Comment by ivanmkc** [comment]
I also opened in internal ticket with the texttospeech team. It seems to be working as of now.

**Comment by arashnh11** [comment]
The issue has been resolved as of today. No further information on the root cause but none related to API keys or podcastfy repo or vanilla TTS libraries.
