### ISSUE TITLE
Add user-defined target output language

### ISSUE THREAD

**Issue by souzatharsis** [souzatharsis/podcastfy#3]
create param that allows users to define output language for transcript and audio

**Comment by Lukafin** [comment]
I tried changing this line in prompt.txt to:
[Language: Output language should be in Slovenian.]

but transcript remained in english.

**Comment by souzatharsis** [comment]
solved in release v0.2.0 #38

please update podcastfy to latest 

language is tricky hence I welcome feedback, See [Conversation Customization](https://github.com/souzatharsis/podcastfy/blob/main/usage/conversation_custom.md) for more details.
