### ISSUE TITLE
generate_podcast should return (audio, transcript)

### ISSUE THREAD

**Issue by souzatharsis** [souzatharsis/podcastfy#33]

**Comment by priyanshuverma-dev** [comment]
@souzatharsis May I Can work on this issue

**Comment by souzatharsis** [comment]
Thanks @priyanshuverma-dev ! After giving it a second thought, I believe we should close this issue. Such a change would break current integrations that expect audio only response. 

@brumar is working a broader issue to have an abstract podcast class to store specific podcast methods and attributes #21

**Comment by souzatharsis** [comment]
won't fix
