### ISSUE TITLE
Add Open in Colab

### ISSUE THREAD

**Issue by souzatharsis** [souzatharsis/podcastfy#35]
To make it easy for someone to quickstart and run examples.
To replicate [podcastfy.ipynb](https://github.com/souzatharsis/podcastfy/blob/main/podcastfy.ipynb)

**Comment by priyanshuverma-dev** [comment]
@souzatharsis may I work on this

**Comment by Devparihar5** [comment]
@souzatharsis, I already did this task, and raised an PR can you please check this and assign it to me
