### ISSUE TITLE
CLI read which config file?

### ISSUE THREAD

**Issue by neohob** [souzatharsis/podcastfy#37]
I have established and configured the .env file in the current directory, but it still reports an error when running 

error message:
401 Client Error: Unauthorized for url: https://r.jina.ai/

**Comment by souzatharsis** [comment]
If you cloned the github repo, include .env file in the root directory and call the CLI from there (that is, not inside podcastfy/ directory)

If you installed via pypi, include a .env file in the same directory you are running you the CLI via bash/terminal.

Of course, make sure you have JINA_API_KEY in your .env file (error message above) among the other required keys.
Please let me know if that helps you. If not, please share a screenshot of your file structure and from where you are running the CLI and I'd be happy to take a look. Thanks!

**Comment by neohob** [comment]
I executed it with PIP to install podcastfy. The following is a screenshot of my current directory structure and execution results.
<img width="1274" alt="image" src="https://github.com/user-attachments/assets/3318869d-3229-4e91-bee2-c43c74a6fe70">

**Comment by souzatharsis** [comment]
solved in release v0.2.0 #38

please update podcastfy to latest
