### ISSUE TITLE
Error converting text to speech with ElevenLabs: status_code: None, body: Voice BrittneyHart not found.

### ISSUE THREAD

**Issue by neohob** [souzatharsis/podcastfy#40]
Error converting text to speech with ElevenLabs: status_code: None, body: Voice BrittneyHart not found.

English or Chinese get same problem, I use pip to install and use, CLI mode call

<img width="840" alt="image" src="https://github.com/user-attachments/assets/27c969ff-6b3f-4431-879e-90293f386c83">
<img width="1277" alt="image" src="https://github.com/user-attachments/assets/19cfd6e8-3287-438c-b910-2aa5a83cc381">

**Comment by souzatharsis** [comment]
Hello @neohob , you need to rename it to "BrittneyHart" in ElevenLabs - I am wrongly using a renamed name in the default config. I will change the default value in the yaml file to a default voice/name so it works our-of-the-box.

Thanks for catching and raising the issue!

**Comment by neohob** [comment]
Thanks, it worked after I renamed the voice.

**Comment by souzatharsis** [comment]
fixed in v0.2.1 release
