### ISSUE TITLE
Integrate with Microsoft's edge TSS for a no-APIKEY solution

### ISSUE THREAD

**Issue by souzatharsis** [souzatharsis/podcastfy#42]
Use Microsoft Edge's online text-to-speech service from Python WITHOUT needing Microsoft Edge or Windows or an API key

https://github.com/rany2/edge-tts

**Comment by ChinoUkaegbu** [comment]
Hi, I'd like to work on this! If I'm not mistaken, the edge-tts model would be included in this [text_to_speech](https://github.com/souzatharsis/podcastfy/blob/main/podcastfy/text_to_speech.py) file?

**Comment by ChinoUkaegbu** [comment]
By the way, I was trying to run an example with ElevenLabs following the docs and got these errors:

![Screenshot (460)](https://github.com/user-attachments/assets/15ee8061-b3c0-4bd8-bb7c-0bfd92150017)

For the first one, I had to get a LangSmith API key and include it in .env. I followed the instructions [here](https://docs.smith.langchain.com/how_to_guides/setup/create_account_api_key#create-an-api-key). This isn't mentioned in the docs I believe, so it might be nice to add that.
And for the second error, I switched out the name in `config.yaml` to one that was supported and that cleared it. 

This was the file I was testing the default settings with on Windows:
```py
from podcastfy.client import generate_podcast

audio_file = generate_podcast(urls=["https://en.wikipedia.org/wiki/Podcast"], tts_model="elevenlabs")
```

**Comment by souzatharsis** [comment]
Hi @ChinoUkaegbu :

1. It would be a major contribution if you integrated podcastfy with edge-tts model. You are right, it would be included in this [text_to_speech](https://github.com/souzatharsis/podcastfy/blob/main/podcastfy/text_to_speech.py).

2. Re: LangSmith API key. That is not required. The referred message is just a warning. It would be required if we used some additional features such as logging LLM traces.

3. Re: ElevenLabs error. Yes, you are right. I was using a custom voice name I have in the config.yaml file. Instead, we should have it as a default voice name so it works out-of-the box. I will fix that.

Thanks for offering to contribute; there is so much we can do here. Please let me know how I could be of help!

**Comment by taowang1993** [comment]
Or you can integrate edge-tts as an OpenAI-compatible API.

https://github.com/travisvn/openai-edge-tts?tab=readme-ov-file

**Comment by taowang1993** [comment]
Hope podcastfy offers openai-compatible api as well.

Then, we can integrate podcastfy into any AI WebUI, like open-webui or librechat.
