### ISSUE TITLE
Add a library that allows to deal with multiple tts backend

### ISSUE THREAD

**Issue by brumar** [souzatharsis/podcastfy#47]
I found this one, but maybe there are others.
https://github.com/KoljaB/RealtimeTTS

Multiple engines are supported, but they abstracted away what an engine is, so that it's possible to add others.
The abstract classe is interesting in its own right https://github.com/KoljaB/RealtimeTTS/blob/master/RealtimeTTS/engines/base_engine.py

If we don't outsource this part, I think it would be a time sink, distanced from the main value of this project.

One important limit of RealtimeTTS is that I think they add only engines that support streaming, but maybe there is still a way to add other engines and not using the streaming capabilities anyway.

**Comment by souzatharsis** [comment]
I'd recommend we implement our own Abstract class to define a common interface for the pre-existing and potential future TTS backends with the minimum required behavior we need for this package. A refactor for 11labs, openai and edge TTS models should be a good test for the proposed Abstract class.

**Comment by brumar** [comment]
Ok, this makes sense too!
