### ISSUE TITLE
Create long form podcasts by building the transcript iteratively

### ISSUE THREAD

**Issue by brumar** [souzatharsis/podcastfy#48]
Asking a LLM to generate long outputs is unreliable and can give to bad results anyway.
So what about enabling something like that (in pseudocode).

```
previous_transcript = ''"
content = [("c1", "c2"), ("c3", "c4")]
for content_chunk in content:
     transcript = build_transcript(previous_transcript, content_chunk)
     previous_transcript = transcript
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/podcastfy) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/souzatharsis/podcastfy/issues/48">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/souzatharsis/podcastfy/issues/48/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/souzatharsis/podcastfy/issues/48/pledge.svg">
</picture>
</a>

**Comment by souzatharsis** [comment]
I think this is a good idea, many use cases beg long-form podcasting with greater detail of the content. Right now both podcastfy and NotebookLM generate quite short conversations.

We would need to update the prompt too, so it has a header (with intros etc), and a footer (with bye bye's). And then your pseudocode in-between.

**Comment by ralyodio** [comment]
Yes, the problem I found with notebook-lm is the podcasts are only 10-15 minutes long. I'm used to 1-2 hour long podcasts. if I can create those I can create my own custom show on topics i like.

**Comment by ralyodio** [comment]
Any update?

**Comment by souzatharsis** [comment]
Hi thanks for the follow up. I was out this week. Once I'm back I will
review and prioritize the backlog.

**Comment by ralyodio** [comment]
Any update?

**Comment by souzatharsis** [comment]
I'm curious about your use case. Why longer podcasts would help solve your
problem?

**Comment by ralyodio** [comment]
I am using this to generate a podcast but when I did it live it was like 1-2 hours long, I'm wanting to use AI to do the podcast now since I don't have the time to keep it going. The issue is these are only like 4-5 minutes long. I want to create a 1-2 hour long podcast.

**Comment by souzatharsis** [comment]
This is interesting.

How do you structure your podcast for it to last so long while remaining
interesting?

Your experience would be helpful to better design a solution for it.

Thanks for sharing.

**Comment by jonjonsson** [comment]
I can't think of a podcast that is 5-7 minutes long, so the use case is pretty clear I would think.  If for example I want to learn about trains using the wiki article. I would want the following segments:

Introduction
The Origins and Early History of Trains
The Technological Evolution of Trains
The Cultural and Economic Impact of Trains
Specialized and Unique Train Systems
Train Safety, Operations, and Components
The Future of Train Transportation
Outro

Using this as "dialogue_structure" in the config and asking for 9000 words for about an hour or so, you still just get 5-7 minutes. It's so surface level you don't really learn anything. 

Issue #126 mentioned [Storm](https://github.com/stanford-oval/storm) which seems similar to what is needed. I haven't tried it yet though.

**Comment by souzatharsis** [comment]
It's Gemini.
Using other base LLMs can give much more detailed and longer outcomes.
You can try it with the local llm option and I'll add openai too.

My understanding is that Storm will help with podcast generation from a
given input topic by doing we search plus nicely structuring processing and
developing the information .

Thanks for your thoughts.

**Comment by jonjonsson** [comment]
Thanks @souzatharsis, I'm looking forward to OpenAI integration. Really appreciate this project!

Any LLM will struggle with generating longform content though. Even GPT-4o-mini that can theoretically can output over 16k tokens doesn't really ever go over 1500 tokens no matter what you ask it.

Storm might be overkill. Generating an output for each dialogue_structure topic individually would go a long way, including anything generated before in the input for context. Eventually would need to tackle too many input tokens problem. Comes with a some challenges for sure...

Anyway just my 2 cents!

**Comment by souzatharsis** [comment]
How would you go about "Generating an output for each dialogue_structure
topic individually"

That's what I was going to use storm for since it has built-in web search +
text cleaning for proper LLM downstream processing.

Thanks for sharing your thoughts.
<http://linkedin.com/in/tharsissouza>

**Comment by jonjonsson** [comment]
The First user prompt would outline the dialogue_structure, and then ask to only generate the first item in the dialogue_structure.
Assistant outputs generation for first item only.
In the same conversation, second user prompt is to generate the second item in the dialogue_structure
Assistant outputs generation for second item only.
etc...

Something like that will make a deeper conversation. However if you are looking into Storm, it will handle all that anyway.

**Comment by souzatharsis** [comment]
Here's a tutorial from Google for creating long-form audio

https://cloud.google.com/text-to-speech/docs/create-audio-text-long-audio-synthesis

**Comment by souzatharsis** [comment]
Here's a solution to overcome the maximum output tokens limit:

https://github.com/mo-haggag/ROG

 _Rolling Output Generation (ROG). This technique allows for fully coherent, context-aware output generation up to the size of the context window, in a single initial call. Applied to OpenAI models, this enables generating 30X the normal output. Generating entire books or extensive codebases is suddenly within reach._

**Comment by souzatharsis** [comment]
@jonjonsson @brumar @ralyodio 

I've managed to implement long-form podcast generation.
Please see sample audio in this discussion - Would love your feedback before I prepare a PR:

https://github.com/souzatharsis/podcastfy/discussions/168

**Comment by souzatharsis** [comment]
This has been implemented - I'd love feedback!

See https://github.com/souzatharsis/podcastfy/blob/main/usage/how-to.md#how-to-generate-longform-podcasts

## [0.3.6] - 2024-11-13

### Added
- Add longform podcast generation support
  - Users can now generate longer podcasts (20-30+ minutes) using the `--longform` flag in CLI or `longform=True` in Python API
  - Implements "Content Chunking with Contextual Linking" technique for coherent long-form content
  - Configurable via `max_num_chunks` and `min_chunk_size` parameters in conversation config
  - `word_count` parameter removed from conversation config as it's no longer used

**Comment by jashton12** [comment]
The trouble I am having with longer form content is that the TTS APIs have token limits. The Gemini TTS max is 5000 tokens and OpenAI 4096. With Elevenlabs and Edge you can push up to 10K but the quality of speech is significantly less natural. Elevenlabs is not bad but still nothing close to Gemini in my opinion. Does anybody have a fix or suggestion to circumvent this so that I can still use the gemini TTS API?

_"Failed to generate audio: 400 Either `input.text` or `input.ssml` is longer than the limit of 5000 bytes. This limit is different from quotas. To fix, reduce the byte length of the characters in this request, or consider using the Long Audio API: https://cloud.google.com/text-to-speech/docs/create-audio-text-long-audio-synthesis."_

I have not tried the long audio synthesis API but my intuition is that it wouldn't work out of the box and may deliver a lower quality of audio too. I may test and report back, but in the meantime any suggestions would be greatly appreciated. I am looking at how to adjust the code so that multiple API calls are made to gemini with the different parts that are generated with longform=True, and then stitching them together. 

Thank you for this package, it's brilliant!
