### ISSUE TITLE
Only generating the introduction

### ISSUE THREAD

**Issue by meetbryce** [souzatharsis/podcastfy#51]
I've got the package running in my app and on the CLI. I'm able to generate audio files successfully but all but once it only generates the introduction. This is happening in both the CLI and using the python package in my app. 

I also tried one of the examples (https://www.souzatharsis.com/) in case there was an issue with the content I was trying to use, but the issue still occurs with that URL.

`poetry run python -m podcastfy.client --url https://bryceyork.com/generative-ai-product-management`
`poetry run python -m podcastfy.client --url https://www.souzatharsis.com/`

**Comment by souzatharsis** [comment]
Fixed in new release v0.2.2. 

Please update podcastfy!

Thanks for reporting it.

**Comment by meetbryce** [comment]
Confirming that the patch fixed my issue.
