### ISSUE TITLE
Please prune the dependencies in requirements.txt

### ISSUE THREAD

**Issue by nwaughachukwuma** [souzatharsis/podcastfy#68]
Hi @souzatharsis, thanks for making this open source.

I don't think all the packages listed in `requirements.txt` are direct dependencies. You can list only the primary dependencies while removing the peer & dev dependencies from the main requirements.txt.

Please let me know if you need any help doing this.

**Comment by souzatharsis** [comment]
Thanks.

requirements.txt has been generated with poetry as below:

`poetry export -f requirements.txt --output requirements.txt --without-hashes --without-urls --only main`

Do you have an alternative recommendation?

**Comment by souzatharsis** [comment]
yes, at a minimum we should remove dev dependencies from requirements.txt

that complicates things a bit as many platforms assume all you need is in requirements.txt in order to deploy your app (gradio, huggingface, etc) but of course one can work around that at deployment phase for target platform

**Comment by nwaughachukwuma** [comment]
I don't want to add to your maintenance workload but I think [astral-sh/uv](https://github.com/astral-sh/uv) is a better option for dependency management. It's 10x faster than poetry, integrates well with [astral-sh/ruff](https://github.com/astral-sh/ruff), and allows tracking all dependencies in one place (the `requirements.txt` file).

**Comment by souzatharsis** [comment]
Sounds good; I've seen uv and it's awesome and perhaps the future.
Contributors can opt to use uv as they wish and generate and push updated requirements.txt from it.
I've added this info to Contributors guide.

I will re-generate requirements.txt without-dev dependencies from poetry and push it as soon as I manage to test it.

**Comment by brumar** [comment]
I am all for uv, maybe rye too. But As @nwaughachukwuma said, I was hesitating to push for this because of the maintainer burden (which I contributed a lot lately ahah) .
A technique I use to prune dependencies is to use pipdeptree and was satisfyed with the results with `pipdeptree --warn silence | grep -E '^\w+'`. But maybe there are other tools for that ?

**Comment by nwaughachukwuma** [comment]
Please feel free to close this, @souzatharsis
