### ISSUE TITLE
An error occurred: 'ConversationConfig' object has no attribute 'items'

### ISSUE THREAD

**Issue by creatorbrew** [souzatharsis/podcastfy#74]
I tried a few different URLs and I do have my .env filled in.  I can't run from the CLI

(venv) root@playground:~/podcastfy# python -m podcastfy.client --url https://nytimes.com2024-10-16 04:09:51,152 - __main__ - ERROR - An error occurred in the process_content function: 'ConversationConfig' object has no attribute 'items'
An error occurred: 'ConversationConfig' object has no attribute 'items'

Any help appreciated if it isn't an issue.

**Comment by souzatharsis** [comment]
This has been fixed in most recent release v0.2.5. 

please update podcastfy

thank you so much for reporting the bug!
