### ISSUE TITLE
Ask for Langsmith API when Attempting Local

### ISSUE THREAD

**Issue by gjnave** [souzatharsis/podcastfy#92]
Hello and thank you for your cool software.

I have followed the directions: dl'd with a pip install, download the llamafile and have the server running.

This is what happens when I run the following command:
python -m podcastfy.client --url www.souzatharsis.com --transcript-only --local 

> D:\Audio\podcastfy\venv\Lib\site-packages\langsmith\client.py:354: LangSmithMissingAPIKeyWarning: API key must be provided when using hosted LangSmith API
>   warnings.warn(
> 2024-10-21 02:57:33,323 - __main__ - INFO - Transcript generated successfully
> Transcript generated successfully: None

**Comment by souzatharsis** [comment]
Please ignore the langsmith message. It's just a warning indicating that we
would need an api key in case we used their tracing capabilities which we
don't. (I'll suppress the warning to avoid confusion)

Your transcript should be in data/transcript by default

We should update the fuction to print this information to the user.

**Comment by souzatharsis** [comment]
simply adding os.environ["LANGCHAIN_TRACING_V2"] = "false"
should remove the warning

I'll push an update with it by default

**Comment by souzatharsis** [comment]
solved
