### ISSUE TITLE
how can I brand the audio output?

### ISSUE THREAD

**Issue by ralyodio** [souzatharsis/podcastfy#99]
I have a podcast called "Byte Broadcast" -- can I make it reference that name?

**Comment by souzatharsis** [comment]
Yes. See
https://github.com/souzatharsis/podcastfy/blob/main/usage/conversation_custom.md

**Comment by ralyodio** [comment]
what's the max word_count I can use?

**Comment by souzatharsis** [comment]
No need to set it up. It will take the default value which is the maximum
allowed.

**Comment by ralyodio** [comment]
so 2000? you have an example that uses 3000
